openapi: 3.0.0
info:
  description: >-
    App that mimics trello application    
  version: 1.0.0
  title: Trello Application
servers: 
  - url: http://localhost:3000/api/
tags:
  - name: Boards
  - name: Lists
  - name: Cards
paths:
  /boards:
    post:
      tags:
        - Boards
      summary: create a new board
      requestBody:
        content: 
          application/json:
            schema:
              $ref: "boards.json"
            example:
              id: 12345
              name: "board1"
              closed: false
              pinned: false
              lists: []
      responses:
        '200':
          description: OK
    get:
      tags:
        - Boards
      summary: Finds all Boards
      responses:
        '200':
          description: successful operation
      
  /boards/{id}:
    get:
      tags:
        - Boards
      summary: Find Board by ID
      description: Returns a single board
      parameters:
        - name: id
          in: path
          description: ID of board to return
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '200':
          description: successful operation
        '404':
          description: Board not found
    
    delete:
      tags:
        - Boards
      summary: Deletes a board
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '200':
          description: OK
        '404':
          description: Board not found
      
    put:
      tags:
        - Boards
      summary: Updated board
      description: This can only be done by the logged in user.
      parameters:
        - name: id
          in: path
          description: id that need to be updated
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '201':
          description: OK
        '404':
          description: board not found
          
  /boards/{id}/lists:
    post:
      tags:
        - Lists
      summary: create a new List in the board
      description: ''
      parameters:
        - name: id
          in: path
          description: board id where the list is created
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000000000
            example: 1234567
      responses:
        '200':
          description: OK
        '405':
          description: Invalid board id
  
  /boards/{bid}/lists/{id}/cards:
    post:
      tags:
        - Cards
      summary: create a new board
      description: ''
      parameters:
        - name: bid
          in: path
          description: Board id 
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100000
            example: 1234
        - name: id
          in: path
          description: List id to create a card
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 10000
            example: 123
      responses:
        '200':
          description: OK
        '405':
          description: Invalid input
      
      